sous-chefs/elasticsearch

Gemfile
- Fixes #269, adds an `elasticsearch_user` resource with provider that creates a user, group, and removes the automatic homedir
- Pins chef to 11.16.4 since chef 12 and many libraries like poise aren't compatible yet
- Adds an `elasticsearch_test` kitchenCI suite that tests edge cases, so the default test suite can test the expected way people use the cookbook
- Tweak rubocop rules to avoid style complaints about methods that are too complex (controversial rule) and compact class styles (also controversial at the moment)
- Updated `README.md` with an example of how to use the `elasticsearch_user` resource
=> Introduce user provider and resource

libraries/resource_configure.rb, libraries/resource_install.rb, libraries/resource_plugin.rb, libraries/resource_service.rb, libraries/resource_user.rb
not sure if this is new to one of the latest releases of chef, but i had to set the default_action for the resources when running this through test-kitchen as the default action was :nothing, otherwise.
=> set default resource actions

libraries/provider_install_package.rb, libraries/resource_install.rb
Hi @karmi 
If you install `1.5.0` and try to update the provider version/url to point to `1.6.0` for example, **assuming that you match the conf path with the one from the elastic package (`/etc/elasticsearch`)**, then you need to be able to pass something like this:
"--force-yes -o Dpkg::Options::='--force-confold'"
Thanks for looking at it, without it there's no way to be able to update nodes in place currently.
=> allow options passing to package provider

README.md, libraries/helpers.rb, libraries/provider_install_source.rb, libraries/provider_plugin.rb, libraries/resource_install.rb, test/fixtures/cookbooks/elasticsearch_test/recipes/default.rb
Before release, rename source provider to tarball, to better match the purpose.
Closes #332.
=> Rename provider source to tarball

README.md
- Add note about chef 12 and standards
- Document configure, service, and plugin resources
Fixes #338.
=> Add lots of additional documentation

README.md
Combined with recent doc improvements by @martinb3, this should resolve #345.
=> Clarify when overriding plugin_dir is necessary

CHANGELOG.md
For some reason github_changelog_generator is generating broken full changelog links. This fixes the  existing ones and the real fix would be to get github_changelog_generator generating correct links.
=> Correct the full changelog links

README.md
According to this comment, packages are now the default install
https://github.com/elastic/cookbook-elasticsearch/issues/384#issuecomment-158693793
=> Updates docs to show package are now default install

README.md
By prefixing code snippets with the type of code, github formats with pretty colors.
=> Makes code examples have color

README.md, attributes/default.rb, test/integration/helpers/serverspec/install_examples.rb
Bump default version to 2.1.1 and add sha256 hashes for rpm/deb/tar of 2.1.1
Fixes #411
=> Update to ES 2.1.1

libraries/provider_plugin.rb
* reorganizes code for DRYness
* install / remove actions both delegate to a new `manage_plugin` method
Note: this is derived from https://github.com/elastic/cookbook-elasticsearch/tree/martinb3/chef_proxy_support and
incorporates its proxy support changes which fixes #415
Fixes #418
=> Plugin removal functionality restored

attributes/default.rb
This adds the checksums for the Elasticsearch 2.3.0 release.
=> Add checksums for 2.3.0

README.md
Using elasticsearch cookbook version 2.3.0 with chef 12.5.1 and passing in `dir '/usr/local'` to `elasticsearch_install` passes on a converge; however, when testing with chef 12.8.1 the following error occurred.
```
$ kitchen converge
-----> Starting Kitchen (v1.6.0)
-----> Using policyfile mode for chef-client
-----> Using policyfile mode for chef-client
-----> Converging <node1-centos-67>...
Preparing files for transfer
Preparing dna.json
Preparing validation.pem
Preparing client.rb
-----> Chef Omnibus installation detected (12.8.1)
Transferring files to <node1-centos-67>
Starting Chef Client, version 12.8.1
Using policy 'companyname-elasticsearch' at revision 'af7908a6d808c0c79da16290631ad75cd6e8100a20459a8ab9bcaae6c81b785f'
resolving cookbooks for run list: …
```
=> Update documentation for dir in elasticsearch_install

libraries/provider_install.rb
Point to determine_download_url instead of non-existent get_package_url.
=> Point to determine_download_url instead of non-existent get_package_url.

libraries/provider_configure.rb
This PR changes logging.yml and elasticsearch.yml file permissions from 0755 to 0644, these files should not be executable.
=> No need for the config yaml files to be executable

libraries/provider_configure.rb, test/integration/helpers/serverspec/configure_examples.rb
The file /etc/default/elasticsearch / /etc/sysconfig/elasticsearch does not need to be executable
=> Fix permissions on environment file

libraries/provider_configure.rb, libraries/resource_configure.rb, templates/default/elasticsearch.in.sh.erb
This PR brings the contents of /etc/default/elasticsearch / /etc/sysconfig/elasticsearch more in line with the format that the Elasticsearch package uses. It removes quotes from vars that don't need it, and strips superfluous spaces from ES_JAVA_OPTS for a cleaner look. Tested on Ubuntu 14.04 and CentOS 6.
It also fixes a tiny cosmetic bug that resulted in env_options being included in ES_JAVA_OPTS because the default was '' instead of nil.
Before:
```
CONF_DIR="/etc/elasticsearch"
DATA_DIR="/usr/share/elasticsearch"
ES_GROUP="elasticsearch"
ES_HEAP_SIZE="496m"
ES_HOME="/usr/share/elasticsearch"
ES_JAVA_OPTS="-server -Djava.awt.headless=true -Djava.net.preferIPv4Stack=true -Xss256k      -XX:+UseParNewGC      -XX:+UseConcMarkSweepGC      -XX:CMSInitiatingOccupancyFraction=75 …
```
=> Improve environment file formatting

.gitignore, .rubocop.yml, .travis.yml, Berksfile, Gemfile, README.md, Rakefile, chefignore, libraries/helpers.rb, libraries/provider_plugin.rb, libraries/provider_service.rb, libraries/resource_install.rb, metadata.rb, test/fixtures/cookbooks/elasticsearch_test/recipes/package.rb, test/fixtures/cookbooks/elasticsearch_test/recipes/tarball.rb, test/integration/helpers/serverspec/chef_examples.rb, test/integration/helpers/serverspec/install_examples.rb, test/integration/helpers/serverspec/spec_helper.rb
Changes broken out into individual commits
=> Minor updates and use cookstyle for linting

README.md, attributes/default.rb, test/integration/helpers/serverspec/install_examples.rb
Hi! Updating the cookbook to be able to handle ES 2.4.1 and install it in lieu of 2.4.0.
=> ES 2.4.1 checksums + use for install/tests default

README.md, attributes/default.rb, libraries/resource_install.rb, test/integration/helpers/serverspec/install_examples.rb
Updated default Elasticsearch version to 5.1.2.
=> Updated to 5.1.2

libraries/provider_user.rb
Support for Chef-client 13.
supports { manage_home: false } on the user resource is deprecated and will be removed in Chef 13, set manage_home false instead at 1 location:
- /var/chef/cache/cookbooks/elasticsearch/libraries/provider_user.rb:25:in `block (2 levels) in <class:UserProvider>'
See https://docs.chef.io/deprecations_supports_property.html for further details.
=> provider_user.rb

libraries/helpers.rb, libraries/provider_configure.rb
@martinb3, I think this is the smallest implementation I could think of to solve the problem described in #598 and earlier in the closed issue #590.
For Chef/Ruby combinations that don't have the problem described in #590 this change acts like a null-op. For those that do, this change forces the Chef::Node::ImmutableArray and Chef::Node::ImmutableMash to cast themselves as pure Ruby arrays and hashes respestively prior to serialization into elasticsearch.yml.
=> [Fixes #598] Support mixed Hash/ImmutableMash configs in elasticsearch.yml

libraries/provider_install.rb, libraries/resource_configure.rb
I updated the package repos to include the 6.x base URLs and remove the path.conf deprecated resource value. 
Related to #593 and  #634
=> Update repos and remove path.conf 

README.md, attributes/default.rb, libraries/resource_install.rb, test/integration/helpers/serverspec/install_examples.rb
This adds support for 5.6.6 
Note: URLS listed on the release page for 5.6.6 are incorrect, they are pointing at the 5.6.5 files.
https://www.elastic.co/downloads/past-releases/elasticsearch-5-6-6
=> Add support for 5.6.6

README.md, attributes/default.rb, libraries/resource_install.rb, test/integration/helpers/serverspec/install_examples.rb
Add hashes and update defaults for 6.1.2. https://www.elastic.co/downloads/past-releases/elasticsearch-6-1-2
=> Add support for 6.1.2

FAQ.md
I experienced [this issue](http://phutchins.com/blog/2017/03/14/java-trust-anchors-error-when-installing-es-plugins/) when installing Elasticsearch from a tarball. The version of Java I installed was OpenJDK 8 (using the `java` cookbook), so maybe this exception happens only on OpenJDK.
I managed to solve it, so I thought the solution could be added to FAQ.
=> Add solution for Java "trust anchors" exception

.rubocop.yml, .travis.yml, metadata.rb, test/fixtures/cookbooks/elasticsearch_test/metadata.rb, test/unit/spec/spec_helper.rb
We're currently seeing:
```
Bundler found conflicting requirements for the Ruby version:
In Gemfile:
Ruby
chef (~> 14.0) was resolved to 14.14.29, which depends on
Ruby (>= 2.4.0)
The command "bundle install --jobs=3 --retry=3 --without kitchen_vagrant kitchen_rackspace kitchen_ec2 development" failed and exited with 6 during .
```
=> Attempt to fix Travis builds

CHANGELOG.md, resources/install.rb, resources/partial/_package.rb
Fix install package to work with custom download_checksum. Currently you cannot specify the download_url or download_checksum so you cannot install newer versions then what already exists!
List any existing issues this PR resolves
=> Fix install package to work with custom download_checksum

resources/install_repository.rb
obvious fix
Remove hard coded version 7 for Debian repository installation
[GH-802]
=> [GH-802] Fix to remove hard coded version 7 for Debian repository
