README.markdown

Added a note to encourage folks to contribute to the `next` branch, and put links to the branch and to the issues being tracked under the 'next' issue label.

Add a note about `next` branch

---

libraries/provider_install_package_dpkg.rb

- Fixes #335, pass package_options to both providers (package and dpkg_package)

Use package options on both providers

---

.travis.yml

Run TravisCI on master branch again, since we renamed next branch to master a bit ago.
Fixes #337.

Run CI on master branch again, after rename

---

libraries/matchers.rb

should fix https://github.com/elastic/cookbook-elasticsearch/issues/367

add missing matchers

---

libraries/provider_plugin.rb

I am trying to setup my local environment to run the test (having some trouble with ruby and bundle setup), meanwhile here is what i suspect as the problem. will run the tests and update the pull request later.
This is a fix for #454

fix plugin remove

---

README.md
attributes/default.rb
test/integration/helpers/serverspec/install_examples.rb

- Added 2.3.4 version
- Rebased off current master

Changed default to be latest 2.3.4 version with sha256 hashes included

---

README.md

One code block was missing syntax

add syntax for code sample

---

attributes/default.rb
libraries/resource_install.rb
templates/default/elasticsearch.yml.erb

Updated the newest version of elastic
Signed-off-by: JJ Asghar <jj@chef.io>

Updated to 5.1.1

---

.travis.yml
attributes/default.rb
libraries/provider_configure.rb
test/fixtures/cookbooks/elasticsearch_test/recipes/doubleinstances.rb
test/integration/helpers/serverspec/configure_examples.rb
test/unit/spec/spec_helper.rb
test/unit/spec/support/supported_platforms.rb

Conflict between rvm in .travis.yml and .ruby-version

Fix ruby version build on travis

---

README.md
attributes/default.rb
libraries/resource_install.rb
test/integration/helpers/serverspec/install_examples.rb

Updated to 5.2.0

---

README.md
attributes/default.rb
libraries/resource_install.rb
test/integration/helpers/serverspec/install_examples.rb

This adds in support for ES 5.2.1 and 5.2.2.

Bump ES version to 5.2.2

---

README.md
attributes/default.rb
test/integration/helpers/serverspec/install_examples.rb

I know 2.4.x is old but would be nice to have the branch updated to the latest 2.4 version.
And maybe a release?
Thanks!

ES 2.4.4 checksums + use for install/tests default

---

libraries/provider_configure.rb

Removes executable flag from 2 configuration files

Do not make configuration files executable

---

README.md
attributes/default.rb
libraries/resource_install.rb
test/integration/helpers/serverspec/install_examples.rb

This adds support for ES 5.3.0

Bump ES version to 5.3.0

---

README.md
attributes/default.rb
libraries/resource_install.rb
test/integration/helpers/serverspec/install_examples.rb

This adds support for ES 5.3.1

Bump ES version to 5.3.1

---

README.md
attributes/default.rb
libraries/resource_install.rb
test/integration/helpers/serverspec/install_examples.rb

This adds support for ES 5.3.2

Bump ES version to 5.3.2

---

README.md
attributes/default.rb
libraries/resource_install.rb
test/integration/helpers/serverspec/install_examples.rb

This adds support for ES 5.4.0

Bump ES version to 5.4.0

---

README.md
attributes/default.rb
libraries/resource_install.rb
test/integration/helpers/serverspec/install_examples.rb

This adds support for ES 5.4.1 and 5.3.3

Bump ES version to 5.4.1 and add support for 5.3.3

---

README.md
attributes/default.rb
libraries/resource_install.rb
test/integration/helpers/serverspec/install_examples.rb

This adds support for 5.4.2 and 5.4.3.

Bump ES version to 5.4.3 and add support for 5.4.2

---

README.md
attributes/default.rb
libraries/resource_install.rb
test/integration/helpers/serverspec/install_examples.rb

This adds support for 5.5.0, 5.4.2 and 5.4.3.

Bump ES version to 5.5.0 and add support for 5.4.2 and 5.4.3

---

README.md
attributes/default.rb
libraries/resource_install.rb
test/integration/helpers/serverspec/install_examples.rb

This add support for version 5.5.2

Add support for 5.5.2

---

README.md
attributes/default.rb
libraries/resource_install.rb
test/integration/helpers/serverspec/install_examples.rb

This add support for version 5.5.3 and 5.6.0

add support for 5.6.0 and 5.5.3

---

README.md
attributes/default.rb
libraries/resource_install.rb
test/integration/helpers/serverspec/install_examples.rb

This adds support for version 5.6.1

---

README.md
attributes/default.rb
libraries/resource_install.rb
test/integration/helpers/serverspec/install_examples.rb

Add support for 5.6.3

---

README.md
attributes/default.rb
libraries/resource_install.rb
test/integration/helpers/serverspec/install_examples.rb

Add support for 5.6.4

---

README.md
attributes/default.rb
libraries/resource_install.rb
test/integration/helpers/serverspec/install_examples.rb

This adds support for ES 5.6.5

Add support for 5.6.5

---

README.md
attributes/default.rb
libraries/resource_install.rb
test/integration/helpers/serverspec/install_examples.rb

This adds support for 5.6.6 and 5.6.7

Update es to 5.6.7

---

README.md
attributes/default.rb
libraries/resource_install.rb
test/integration/helpers/serverspec/install_examples.rb

Add support for ES 6.2.0/6.2.1/6.2.2

---

README.md
attributes/default.rb
libraries/resource_install.rb
test/integration/helpers/serverspec/install_examples.rb

add support for 6.2.4

---

README.md
attributes/default.rb
libraries/resource_install.rb
test/integration/helpers/serverspec/install_examples.rb

Add support for 5.6.10

---

README.md
attributes/default.rb
libraries/resource_install.rb
test/integration/helpers/serverspec/install_examples.rb

This adds support for elasticsearch 5.6.11

Update es to 5.6.11

---

README.md
attributes/default.rb
libraries/resource_install.rb
test/integration/helpers/serverspec/install_examples.rb

Add support for 6.3.0

---

README.md
attributes/default.rb
libraries/resource_install.rb
test/integration/helpers/serverspec/install_examples.rb

Update es to 6.3.1

---

README.md
attributes/default.rb
libraries/resource_install.rb
test/integration/helpers/serverspec/install_examples.rb

This provides support for 6.3.0, 6.3.1, and 6.4.0

Update es to 6.4.0

---

README.md
attributes/default.rb
libraries/resource_install.rb
test/integration/helpers/serverspec/install_examples.rb

This adds support for ES 6.4.1

Add support for 6.4.1

---

README.md
attributes/default.rb
libraries/resource_install.rb
test/integration/helpers/serverspec/install_examples.rb

This adds support for Elasticsearch 6.4.3

Add support for 6.4.3

---

README.md
attributes/default.rb
libraries/resource_install.rb
test/integration/helpers/serverspec/install_examples.rb

This adds support for 6.5.0 and 6.5.1

Update es to 6.5.1

---

README.md
attributes/default.rb
libraries/resource_install.rb
test/integration/helpers/serverspec/install_examples.rb

This adds support for ES 6.5.2

Update es to 6.5.2

---

README.md
attributes/default.rb
libraries/resource_install.rb
test/integration/helpers/serverspec/install_examples.rb

Update es to 6.5.3

---

README.md
attributes/default.rb
libraries/resource_install.rb
test/integration/helpers/serverspec/install_examples.rb

Updates for 6.5.4

---

README.md
attributes/default.rb
libraries/resource_install.rb
test/integration/helpers/serverspec/install_examples.rb

Updates for 5.6.14

---

README.md
attributes/default.rb
libraries/resource_install.rb
test/integration/helpers/serverspec/install_examples.rb

Rebased from https://github.com/elastic/cookbook-elasticsearch/pull/701/files.

Add support for 6.6.0

---

.markdownlint-cli2.yaml
CHANGELOG.md
kitchen.dokken.yml
kitchen.exec.yml
kitchen.global.yml

This PR will standardise the files we have with out agreed spec in sous-chefs/repo-management.
This repo has been identified by topic(s) of chef-cookbook

Automated PR: Standardising Files
